name: Deploy Service
run-name: ${{ inputs.app_name || github.event.client_payload.app_name }} @ ${{ inputs.commit_sha || github.event.client_payload.commit_sha }}

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      commit_sha:
        required: true
        type: string

  repository_dispatch:
    types: [deploy]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Set variables (for repository_dispatch)
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "APP_NAME=${{ github.event.client_payload.app_name }}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${{ github.event.client_payload.commit_sha }}" >> $GITHUB_ENV

      - name: Set variables (for workflow_call)
        if: github.event_name == 'workflow_call'
        run: |
          echo "APP_NAME=${{ inputs.app_name }}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${{ inputs.commit_sha }}" >> $GITHUB_ENV

      - name: Checkout app repo
        uses: actions/checkout@v4
        with:
          repository: madhan-kumar-revature/${{ inputs.app_name || github.event.client_payload.app_name }}
          ref: ${{ inputs.commit_sha || github.event.client_payload.commit_sha }}

      - name: Listing Files
        run: ls -al

      - name: Build Docker Image
        run: echo "Building $APP_NAME at $COMMIT_SHA"
