name: Deploy Service
run-name: ${{ github.event.client_payload.app_name }} || ${{ github.event.client_payload.commit_sha }}

on:
  repository_dispatch:
    types: [deploy]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4
        with:
          repository: madhan-kumar-revature/${{ github.event.client_payload.app_name }}
          ref: ${{ github.event.client_payload.commit_sha }}

      - run: echo "Building..."

  Deploy-Dev:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event.client_payload.deploy_dev == true
    steps:
      - run: echo "Deploying to Dev"

  Deploy-QA:
    runs-on: ubuntu-latest
    needs: Deploy-Dev   # or Build (your choice)
    if: github.event.client_payload.deploy_qa == true
    environment: Qa
    steps:
      - run: echo "Deploying to QA"
