name: Deploy Service
run-name: ${{ github.event.client_payload.app_name }} || ${{ github.event.client_payload.commit_sha }}

on:
  repository_dispatch:
    types: [deploy]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4
        with:
          repository: madhan-kumar-revature/${{ github.event.client_payload.app_name }}
          ref: ${{ github.event.client_payload.commit_sha }}

      - run: echo "Building..."

  Build-Dev:
    name: Dev Build
    runs-on: ubuntu-latest
    needs: Build
    if: github.event.client_payload.deploy_dev == true
    environment: Dev
    steps:
      - run: echo "Building for Dev"

  Deploy-Dev:
    name: Dev Deploy
    runs-on: ubuntu-latest
    needs: Build-Dev
    if: github.event.client_payload.deploy_dev == true
    environment: Dev
    steps:
      - run: echo "Deploying to Dev"

  Build-Qa:
    name: Qa Build
    runs-on: ubuntu-latest
    needs: Build-Dev
    if: github.event.client_payload.deploy_qa == true
    environment: Qa
    steps:
      - run: echo "Building for QA"

  Deploy-Qa:
    name: Qa Deploy
    runs-on: ubuntu-latest
    needs: Build-Qa
    if: github.event.client_payload.deploy_qa == true
    steps:
      - run: echo "Deploying to QA"

  Build-Staging:
    name: Staging Build
    runs-on: ubuntu-latest
    needs: Build-Qa
    environment: Staging
    steps:
      - run: echo "Building for Staging"

  Deploy-Staging:
    name: Staging Deploy
    runs-on: ubuntu-latest
    needs: Build-Staging
    steps:
      - run: echo "Deploying to Staging"

  Build-Prod:
    name: Prod Build
    runs-on: ubuntu-latest
    needs: Build-Staging
    environment: Prod
    steps:
      - run: echo "Building for Prod"

  Deploy-Prod:
    name: Prod Deploy
    runs-on: ubuntu-latest
    needs: Build-Prod
    steps:
      - run: echo "Deploying to Prod"
